In [4]:
import numpy as np

# Broadcast
operações elemento a elemento entre arrays de dimensões diferentes

In [5]:
A=np.array([[11.,12.],
            [21.,22.]])
B=np.array([[33.,44.],
            [55.,66.]])
x=np.array([[1.,2.]])
y=np.array([[4.],
            [5.]])

In [6]:
print(A*B)

[[  363.   528.]
 [ 1155.  1452.]]


In [7]:
print(A*x)

[[ 11.  24.]
 [ 21.  44.]]


In [8]:
print(A*y)

[[  44.   48.]
 [ 105.  110.]]


In [9]:
print(x*y)

[[  4.   8.]
 [  5.  10.]]


In [10]:
print(y*x)

[[  4.   8.]
 [  5.  10.]]


# arrays de dimensão n

sem inicializaçção específica

In [11]:
z=np.ndarray([2,2,2],dtype=np.int)
z

array([[[140278098521016,  94471952562032],
        [140278102839408, 140278102744344]],

       [[140277860670832, 140278102121976],
        [140277952615600, 140278102836088]]])

In [12]:
for i in range(2):
    for j in range(2):
        for k in range(2):
            z[i,j,k]=100*(i+1)+10*(j+1)+(k+1)
z

array([[[111, 112],
        [121, 122]],

       [[211, 212],
        [221, 222]]])