In [28]:
import numpy as np

# Matrizes podem ser representadas usando arrays de 2 dimensões

In [29]:
a = np.array([[1, 2],
              [ 3, 4]])
a

array([[1, 2],
       [3, 4]])

In [30]:
b = np.array([[5, 6],
              [ 7, 8]])
b

array([[5, 6],
       [7, 8]])

* conferir dimensões

In [31]:
a.shape

(2, 2)

# Transposta

In [32]:
a.T

array([[1, 3],
       [2, 4]])

# Operações elemento a elemento

* soma

In [33]:
a+b

array([[ 6,  8],
       [10, 12]])

* subtração

In [34]:
a-b

array([[-4, -4],
       [-4, -4]])

* multplicação

In [35]:
a*b

array([[ 5, 12],
       [21, 32]])

* divisão

In [36]:
a/b

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

* potência

In [37]:
a**b

array([[    1,    64],
       [ 2187, 65536]])

* funções elementais

In [38]:
np.log(a)

array([[ 0.        ,  0.69314718],
       [ 1.09861229,  1.38629436]])

# Operações matriciais

* multiplicação matricial

In [39]:
a@b

array([[19, 22],
       [43, 50]])

In [40]:
b@a

array([[23, 34],
       [31, 46]])

* representação de vetores por matriz coluna

In [41]:
v1= np.array([[1],[2]])
v1

array([[1],
       [2]])

In [42]:
v2= np.array([[3],[4]])
v2

array([[3],
       [4]])

In [43]:
v1.T@v2

array([[11]])

In [44]:
v2.T@v1

array([[11]])

In [45]:
v1@v2.T

array([[3, 4],
       [6, 8]])

In [46]:
v2@v1.T

array([[3, 6],
       [4, 8]])

# matriz identidade

In [47]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

# matriz de (1)s

In [48]:
np.ones([2,2])

array([[ 1.,  1.],
       [ 1.,  1.]])

# matriz nula

In [49]:
np.zeros([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

# cuidado

Os arrays de uma dimensão não são adequados para representar vetor

In [51]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [52]:
y=np.array([4,5,6])
y

array([4, 5, 6])

* conferir dimensões

In [53]:
x.shape

(3,)

In [54]:
x.T

array([1, 2, 3])

> não tem transposta

In [55]:
x @ y

32

> operador da multiplicação matricial se comporta como produto escalar