# Problema

$x+y=1$

$x-2y=2$

# Solução

$3y=-1$

$y=-\frac{1}{3}$

$x=1+\frac{1}{3}$

# Matricialmente

$Ax=b$

$x=A^{-1}b$

In [1]:
import numpy as np
A=np.array([[1.,1.],[1.,-2.]])
b=np.array([[1.,2.]]).T

In [2]:
print(b) #em pé

[[ 1.]
 [ 2.]]


In [3]:
A**-1

array([[ 1. ,  1. ],
       [ 1. , -0.5]])

In [4]:
from numpy import linalg as la
Ainv=la.inv(A)

In [5]:
Ainv@A

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [6]:
v=Ainv@b
print(v)

[[ 1.33333333]
 [-0.33333333]]


In [7]:
v=la.solve(A,b)
print(v)

[[ 1.33333333]
 [-0.33333333]]
